const data = [
  {
    img: "https://imagesavatar-static01.italki.com/1T106680910_Avatar.jpg",
    title: "Julian Buff- French",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 Learners)",
    prevPrice: "Rs 10000",
    newPrice: "Rs 5000",
    language: "French",
  },
  {
    img: "https://imagesavatar-static01.italki.com/10T011598390_Avatar_1.jpg",
    title: "Mary Sato",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(1483 Learners)",
    prevPrice: "Rs 1400",
    newPrice: "Rs 1200",
    language: "French",
  },

  {
    img: "https://imagesavatar-static01.italki.com/2T056799840_Avatar_1.jpg",
    title: "Ejderha K (French)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(11123 Learners)",
    prevPrice: "Rs 18000",
    newPrice: "Rs 12000",
    language: "French",
  },
  {
    img: "https://imagesavatar-static01.italki.com/2T108986200_Avatar_1.jpg",
    title: "Isabelle (French)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(48523 Learners)",
    prevPrice: "Rs 19000",
    newPrice: "Rs 16000",
    language: "French",
  },
  {
    img: "https://imagesavatar-static01.italki.com/3T083956790_Avatar_1.jpg",
    title: "Mourad Hamdi (German)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(7123 Learners)",
    prevPrice: "Rs 10000",
    newPrice: "Rs 9000",
    language: "German",
  },
  {
    img: "https://imagesavatar-static01.italki.com/5T069452590_Avatar.jpg",
    title: "Francois Expert (German)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(1488 Learners)",
    prevPrice: "Rs 18000",
    newPrice: "Rs 10000",
    language: "German",
  },

  {
    img: "https://imagesavatar-static01.italki.com/3T039649266_Avatar_1.jpg",
    title: "Leo Monteux (German)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(12773 Learners)",
    prevPrice: "Rs 14000",
    newPrice: "Rs 5990",
    language: "German",
  },

  {
    img: "https://imagesavatar-static01.italki.com/6T051814560_Avatar_1.jpg",
    title: "Cristophe Leb (French)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(7853 Learners)",
    prevPrice: "Rs 14000",
    newPrice: "Rs 8200",
    language: "French",
  },

  {
    img: "https://imagesavatar-static01.italki.com/1T064544920_Avatar_1.jpg",
    title: "Esther (French)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(1003 Learners)",
    prevPrice: "Rs 8000",
    newPrice: "Rs 2000",
    language: "French",
  },

  {
    img: "https://imagesavatar-static01.italki.com/1T016893063_Avatar_1.jpg",
    title: "Park J (French)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 Learners)",
    prevPrice: "Rs 1400",
    newPrice: "Rs 1000",
    language: "French",
  },
  {
    img: "https://imagesavatar-static01.italki.com/3T081647870_Avatar_1.jpg",
    title: "Karl Otto (French)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(9874 Learners)",
    prevPrice: "Rs 18000",
    newPrice: "Rs 15000",
    language: "French",
  },
  {
    img: "https://imagesavatar-static01.italki.com/1T043239960_Avatar_1.jpg",
    title: "Hanna Y (French)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(5123 Learners)",
    prevPrice: "Rs 14000",
    newPrice: "Rs 11150",
    language: "French",
  },
  {
    img: "https://imagesavatar-static01.italki.com/T127324700_Avatar_1.jpg",
    title: "Roma Z (French)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(10123 Learners)",
    prevPrice: "Rs 1800",
    newPrice: "Rs 1599",
    language: "French",
  },
  {
    img: "https://imagesavatar-static01.italki.com/22T029707290_Avatar_1.jpg",
    title: "Travis Martinez (French)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(7819 Learners)",
    prevPrice: "Rs 1800",
    newPrice: "Rs 1500",
    language: "French",
  },

  {
    img: "https://imagesavatar-static01.italki.com/5T014035380_Avatar_1.jpg",
    title: "Alex Gram (French)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(78123 Learners)",
    prevPrice: "Rs 20000",
    newPrice: "Rs 18000",
    language: "French",
  },
  {
    img: "https://imagesavatar-static01.italki.com/21T062415230_Avatar_1.jpg",
    title: "Chex Skate (German)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(4180 Learners)",
    prevPrice: "Rs 15000",
    newPrice: "Rs 14000",
    language: "German",
  },
  {
    img: "https://imagesavatar-static01.italki.com/4T122559790_Avatar_1.jpg",
    title: "Liuang T (Japanese)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(8923 Learners)",
    prevPrice: "Rs 14000",
    newPrice: "Rs 7100",
    language: "Japanese",
  },
  {
    img: "https://imagesavatar-static01.italki.com/T086237920_Avatar_1.jpg",
    title: "Mark (Japanese)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(3000 Learners)",
    prevPrice: "Rs 1900",
    newPrice: "Rs 1400",
    language: "Japanese",
  },
  {
    img: "https://imagesavatar-static01.italki.com/T069249100_Avatar_1.jpg",
    title: "Joe Smith (Japanese)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(12883 Learners)",
    prevPrice: "Rs 14000",
    newPrice: "Rs 5100",
    language: "Japanese",
  },
  {
    img: "https://imagesavatar-static01.italki.com/8T071965910_Avatar_1.jpg",
    title: "Chunky H (English)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(1023 Learners)",
    prevPrice: "Rs 15000",
    newPrice: "Rs 10000",
    language: "English",
  },
  {
    img: "https://imagesavatar-static01.italki.com/1T062629800_Avatar_1.jpg",
    title: "Affrinder J (English)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 Learners)",
    prevPrice: "Rs 1000",
    newPrice: "Rs 990",
    language: "English",
  },
  {
    img: "https://imagesavatar-static01.italki.com/3T029739050_Avatar_1.jpg",
    title: "Dill Jacob (English)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 Learners)",
    prevPrice: "Rs 4000",
    newPrice: "Rs 3150",
    language: "English",
  },
  {
    img: "https://imagesavatar-static01.italki.com/8T071965910_Avatar_1.jpg",
    title: "Emma Trias (French)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(1203 Learners)",
    prevPrice: "Rs 1400",
    newPrice: "Rs 200",
    language: "French",
  },

  {
    img: "https://imagesavatar-static01.italki.com/2T108207930_Avatar_1.jpg",
    title: "Lee Bernald (English) ",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(17823 Learners)",
    prevPrice: "Rs 15000",
    newPrice: "Rs 8500",
    language: "English",
  },
  {
    img: "https://imagesavatar-static01.italki.com/8T086652800_Avatar_1.jpg",
    title: "Chunky H (English)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(123 Learners)",
    prevPrice: "Rs 16000",
    newPrice: "Rs 15000",
    language: "English",
    
  },
  {
    img: "https://imagesavatar-static01.italki.com/T066914800_Avatar_1.jpg",
    title: "Amore Grenald (English)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(7843 Learners)",
    prevPrice: "Rs 15000",
    newPrice: "Rs 10000",
    language: "English",
  },
  {
    img: "https://imagesavatar-static01.italki.com/4T050333400_Avatar_1.jpg",
    title: "Adele R (English)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(8923 Learners)",
    prevPrice: "Rs 6500",
    newPrice: "Rs 5000",
    language: "English",
  },
  {
    img: "https://imagesavatar-static01.italki.com/T044483690_Avatar_1.jpg",
    title: "Benno T (German)",
    // star: <AiFillStar className="rating-star" />,
    reviews: "(78573 Learners)",
    prevPrice: "Rs 22000",
    newPrice: "Rs 20000",
    language: "German",
  },
];

export default data;